### ISSUE TITLE
Unique icon name for CuteCom

### ISSUE THREAD

**Issue by Jacajack** [neundorf/CuteCom#11]
Hi!

Currently CuteCom uses same icon as terminal, because `openterm` icon  is a symlink to terminal icon.
Recently I wanted to contribute CuteCom icon (https://github.com/numixproject/circle-core/pull/3401) to [Numix Circle](https://github.com/numixproject/circle-core) icon theme and we faced problem, because we would have to overwrite `openterm` icon with serial-terminal-like icon which I made for CuteCom.

I'd like to ask if it's possible to change `cutecom.desktop` icon line to something unique like `cutecom` (as in openSUSE distribution desktop file), to allow other icons to be used and avoid the risk of breaking other apps' icons?
```
[Desktop Entry]
Encoding=UTF-8
Name=CuteCom
MimeType=
GenericName=Serial Terminal
Exec=cutecom
Icon=cutecom
Path=
Type=Application
Terminal=0
X-KDE-StartupNotify=false
```

Also, current desktop file makes it impossible to distinguish CuteCom from terminal, when both are launched, which is kind of annoying, when you have to switch between them multiple times.
![selection_865](https://cloud.githubusercontent.com/assets/6173262/18204862/4fd83502-711f-11e6-96d4-16431ad08d15.png)

Thank you in advance :)

**Comment by cyc1ingsir** [comment]
Hi @Jacajack,

I changed it.
I guess the openterm icon was used originally to have an icon for CuteCom at all.
The screenshot you posted over at numixproject/circle-core indicates you are using a rather old version of CuteCom.
You might have to contact the distribution's package maintainer to provide a new version for your distribution containing the new desktop file.

**Comment by Jacajack** [comment]
Thanks! :+1:

I went to Launchpad in order to check who is the `cutecom` package maintainer, and found out this:

![selection_951](https://cloud.githubusercontent.com/assets/6173262/18587721/b00243d2-7c23-11e6-8017-a8f5094b3578.png)

and unfortunately, this:

![selection_952](https://cloud.githubusercontent.com/assets/6173262/18587729/b419041a-7c23-11e6-8835-eae92b4befee.png)

I'm not really into publishing packages and how Launchpad works, but I guess that there should be some way to reassign package maintainer. Maybe you should ask for that. It would be nice to have newer versions of CuteCom available from packages. :)

**Comment by cyc1ingsir** [comment]
@Jacajack 
Sorry, I'm not using Ubuntu at all. So I can't provide any Ubuntu packages.
As far as I know Roman used to provide the Debian packages.
You might try to contact directly.
