### ISSUE TITLE
Create a button to send CTRL+Z

### ISSUE THREAD

**Issue by FalkenZarkan** [neundorf/CuteCom#20]
When you want to send a SMS, you absolutly need to press Ctrl+Z to terminate the message and send it to the modem. It's not possible actually to enter that special character into the input line.
Could it be possible to create a button to send that character into the input buffer ?

**Comment by slapab** [comment]
Hi,

some of control characters (Ctrl+Q, Ctrl+S, Ctrl+C) are supported and implemented in way which are send directly to the device.

In Unicode encoding there are [symbols](http://unicode-table.com/en/#241A) (range: 0x2400 - 0x241F) that are graphical representations of control characters. They can be pasted to the input box and they will be displayed properly, but current implementation of sending input buffer uses function that does not support non-Latin1 characters.

One suggestion is to add support of more shortcuts to send more control characters. But in my opinion we should also add some kind of switch which will allow to put the control character directly to the device or graphical symbol to the text box. During sending of input buffer it will search for discussed Unicode characters, and they will be replaced with proper value.

@cyc1ingsir, what do you think?

**Comment by cyc1ingsir** [comment]
Thanks for your suggestion @slapab . It sounds rather good to me.
What I wouldn't like is to add a UI control just to send one specific control character as I my opinion, this would clutter the UI to much.
About your suggestion regarding the UTF-8 symbols: To make entering the symbol easier for the user, it would be cool, to show some sort of a matrix with the control characters displayed on it. Maybe something similar to a virtual keyboard.  
As you said, (Ctrl+Q, Ctrl+S, Ctrl+C) are sent to the device directly. To support the original reported use case, after pressing Ctrl+Z, CuteCom needed to send the input buffer's content prior to sending the control character. I'm unsure, if this was intuitive.

**Comment by cyc1ingsir** [comment]
Hi @FalkenZarkan,
have a look at the feature just added by slapab. This should support your use case.
Just let us know.

**Comment by DataMedics** [comment]
This feature would be really handy for use in hard drive interfacing (for data recovery) as well.  We often need to rap on ctrl+z very rapidly when a hard drive is first spinning up to initiate a ttl connection before it fully initializes.  So having a button for this or having it pass through would be really nice.

**Comment by cyc1ingsir** [comment]
Issue moved to https://gitlab.com/cutecom/cutecom/issues/22
