### ISSUE TITLE
Checkboxes "Display Ctrl Chars" and "Show Timestamp", incorrect init

### ISSUE THREAD

**Issue by KarlZeilhofer** [neundorf/CuteCom#23]
First, Thank you very much for the improvement of cutecom - very nice done!
is there any donation button?

As the title sais, these checkboxes are incorrectly set initially (after a first run and compiled with QtCreator in debug mode). Once you toggle them, the settings are applied correctly. 

Greets, Karl

**Comment by cyc1ingsir** [comment]
Well spotted! Thaks for the report.
The above commit should fix this.

**Comment by KarlZeilhofer** [comment]
great, thanks!
