### ISSUE TITLE
Crashes on device disconnect.

### ISSUE THREAD

**Issue by sprnza** [neundorf/CuteCom#24]
Hi there!
Unfortunately the update brought a critic flaw in the app. It's started craching on device disconnect. Previous version was just disconnecting and everything I needed is just hit the Connect button to have it working again.

**Comment by sprnza** [comment]
Sorry, I came from AUR and CuteCom was updated there up to 0.30.4 just now. So I'm talking about 0.30.4

**Comment by sprnza** [comment]
"Previous version" is QT4 version (0.22.0) which doesn't crash

**Comment by cyc1ingsir** [comment]
Version 0.30.4 is more or less a rewrite.
I don't have an Arch Linux distribution running anywhere. I'll have to see if I can replicate this somehow.

**Comment by cyc1ingsir** [comment]
Installed Arch Linux on Virtualbox (osboxes KDE image). Upgraded it and installed yaourt to be able to install cutecom.
Currently it is build using Qt version 5.7.1.
Tested it. Opened and closed the connection several times. Disconnected the device physically.
==> not crashing
