### ISSUE TITLE
Cannot open file ':/images/info.svg'

### ISSUE THREAD

**Issue by KnightSch** [neundorf/CuteCom#26]
------- system:ubuntu 14.04, uses Qt version 5.2.1 CuteCom 0.30.4 -------
when i run 'sudo cutecom' under the terminal, the log is show below:
"
Cannot open file ':/images/info.svg', because: Unknown error
Cannot open file ':/images/info.svg', because: Unknown error
setting current session to:  "Default" 
MainWindow::MainWindow(QWidget*, const QString&) calculated height:  31 
Cannot open file ':/images/terminal.svg', because: Unknown error
Cannot open file ':/images/terminal.svg', because: Unknown error
Cannot open file ':/images/terminal.svg', because: Unknown error
Cannot open file ':/images/terminal.svg', because: Unknown error
"
In addition, there are some occasions, it is necessary to send characters in a loop, loop interval can be milliseconds or seconds, whether to consider adding this feature？thanks

**Comment by cyc1ingsir** [comment]
About the SVG icons:
Maybe the Qt SVG module has not been installed on your system:
http://stackoverflow.com/a/29233939

Could you please add a separate issue for the loop feature. Thanks

**Comment by cyc1ingsir** [comment]
Is it working now?

**Comment by KnightSch** [comment]
Because I leave Friday, so there is no test environment. I think that will be fine after install SVG modules, so shut down this issue, sorry about that !
Today I install 'libqt5svg5 libqt5svg5-dev libqt5svg5-private-dev' and modify CMakeLists.txt  of the following part:
”
find_package(Qt5Svg REQUIRED)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 ${Qt5Svg_EXECUTABLE_COMPILE_FLAGS}")
qt5_use_modules(cutecom Core Gui Widgets SerialPort Svg)
target_link_libraries(cutecom Qt5::Svg)
“
After a recompile， problems did not improve, but to replace the ‘: / images / *. SVG ' to '. / images / *. SVG ', it seems fine.

**Comment by cyc1ingsir** [comment]
> but to replace the `:/images/*.SVG` to `./images/*` 

This doesn't look right since `:/images` refers to the QtResource (http://doc.qt.io/qt-5/resources.html)
defined in `resources.qrc`

**Comment by cyc1ingsir** [comment]
It doesn't seem to be a general issue.
So I'm closing this.
