### ISSUE TITLE
Option to select line ending characters

### ISSUE THREAD

**Issue by ccrause** [neundorf/CuteCom#33]
In the original CuteCom (0.22) there is an option to select the character sequence for a line ending.  This is useful because not all devices terminate strings with a \r\n sequence.  In particular I'm programming a microcontroller and the serial communication only returns a carriage return character because I'm trying to save a couple of bytes.

**Comment by cyc1ingsir** [comment]
Line endings sent by devices are assumed to be `\n`. I can't remember having changed that behavior in version 0.30 and above.
However, starting with release 0.40 a single `\r` will be treated as a newline if CR is selected for input termination.
![line-endings](https://cloud.githubusercontent.com/assets/2297037/21965518/0243bd4a-db62-11e6-98aa-28db46f955a2.jpg)
Does this solves your issue?

**Comment by ccrause** [comment]
Thanks cyc1ingsir, that option would work for my case.
