### ISSUE TITLE
Not all chars are printed in ASCII part in hex mode

### ISSUE THREAD

**Issue by mastykin** [neundorf/CuteCom#35]
![hex](https://cloud.githubusercontent.com/assets/14311007/22140800/1a5262de-df08-11e6-91f3-616bc54435aa.jpg)

**Comment by cyc1ingsir** [comment]
I'm not able to reproduce this using the DataDisplayTester (https://github.com/cyc1ingsir/DataDisplayTester) (unit) testing project
![hex_display](https://cloud.githubusercontent.com/assets/2297037/22160538/4ea87760-df46-11e6-88e1-0813e690722a.jpg)

but I haven't applied your recent changes to it yet.

**Comment by mastykin** [comment]
I was testing without my recent changes. I think the problem is in 0x00 bytes (that you don't have in your test picture).

**Comment by cyc1ingsir** [comment]
this should have been fixed by PR #39
