### ISSUE TITLE
Significant CPU usage with massive outputs.

### ISSUE THREAD

**Issue by mastykin** [neundorf/CuteCom#37]
Hi.
My sensor is providing many data on 100Hz,
and I see significant CPU usage compared to old CuteCom.
I think the problem is in QPlainTextEdit.
In #34 there is a suggestion how to solve it.
It does batch insertText() operations on timer.
CPU usage is reduced from 40% to 10%.
Dmitry

**Comment by cyc1ingsir** [comment]
I haven't been able to test your PR yet. Not having a device available which sends this amount of data within a short time, it would be great, if someone else would like have a go on testing the changes.
If no one can do this, I might just go ahead and merge the PR.
In any case one good way of testing might be using the DataDisplayTester (https://github.com/cyc1ingsir/DataDisplayTester). I'll try to apply the PR's changes asap.

**Comment by slapab** [comment]
This issue can be reproduced with for example two usb-uart converters connected together.  The first converter must be opened in cutecom, and the second will be a transmitter. I wrote a simple bash script that sends some data in  the loop with delay about 10ms to the transmitter.

```
#!/bin/bash

dev="/dev/ttyUSB0"
msg="testing message, value 1234, 567890 - "

stty -F "$dev" 921600 cs8 -cstopb

for i in $(seq 1 10000) ; do
        echo "$msg / $i" >> "$dev"
        sleep 0.01
done
```

I've noticed that value of CPU usage depends from CPU model. I've tested on the old core 2 duo and actually the CPU usage was about 40% to 50% with timestamp and displaying ctrl characters. With enabled  output in the hex mode, CPU usage grew up to 70-80%. On the i7 core in the first case usage was max 10% and in the hex mode was about 30%. But performing tests I couldn't hang out the cutecom.

Proposed option to buffer incoming data and printing them out after dozens of milliseconds is in my opinion good performance optimization.

I have tested and reviewed provided PR. In each case the CPU usage is reduced.

**Comment by mastykin** [comment]
> performing tests I couldn't hang out the cutecom
I did it in hex mode just clicking once by mouse inside output area. CPU started to grow yet more, output got slower, buttons became less responsive, and after closing CuteCom, it had not disappeared from tasks.

**Comment by cyc1ingsir** [comment]
Issue moved to https://gitlab.com/cutecom/cutecom/issues/37
