### ISSUE TITLE
Inline completions of input line tend to send wrong commands

### ISSUE THREAD

**Issue by mastykin** [neundorf/CuteCom#38]
Hello.
I have problems with inline completions of input line. It would be better if their database would be sorted as "most recent first", but "oldest first" make me accidentally sending erroneous data. In this case I prefer QCompleter::PopupCompletion, that does not autocomplete on enter, but I may choose by up/down buttons if needed.
Dmitry

**Comment by cyc1ingsir** [comment]
We could change that.
Would be interested in other user's thoughts on that issue

**Comment by cyc1ingsir** [comment]
Issue moved to https://gitlab.com/cutecom/cutecom/issues/38
