### ISSUE TITLE
Filtering history based on current input

### ISSUE THREAD

**Issue by michal-narajowski** [neundorf/CuteCom#40]
It would be nice to filter the commands history based on the input, to be able to find a similar command used much earlier. Would be great if it was possible to then select a line with up and down arrows.

**Comment by mastykin** [comment]
It's similar to #38. Popup completion will help. But this will search only strings with identical beginning. It's not a search by any part of string.

**Comment by cyc1ingsir** [comment]
For further discussion please use #38
