### ISSUE TITLE
Optional dark theme

### ISSUE THREAD

**Issue by michal-narajowski** [neundorf/CuteCom#41]
It would be nice to have a dark theme option. I already hacked the dark theme locally using [this theme](https://github.com/ColinDuquesnoy/QDarkStyleSheet), but it would require some work, to make it optional.

**Comment by CieNTi** [comment]
Please check PR:#62

**Comment by cyc1ingsir** [comment]
Issue moved to https://gitlab.com/cutecom/cutecom/issues/41
