### ISSUE TITLE
XModem transfer fails

### ISSUE THREAD

**Issue by simeonfelis** [neundorf/CuteCom#46]
XModem transfer fails:

A dialog with following message appears:

<pre>
Could not start sx
</pre>

From stdout/stderr:
<pre>
sx exited with: 2 QProcess::ExitStatus(NormalExit)
</pre> 

sx binary:
<pre>
which sx
/usr/bin/sx
</pre>

sx version:

<pre>
pacman -Si lrzsz 
Name                     : lrzsz
Version                  : 0.12.20-5
</pre>

Using cutecom 0.40.0-1 on ArchLinux

**Comment by simeonfelis** [comment]
I applied the patch from commit 27949f877381760e6c27ef7073bc320f8358789a to 0.40.0 and it works. Thank you!

**Comment by cyc1ingsir** [comment]
Fixed thanks to the #47 from @slapab
