### ISSUE TITLE
Purposal: Receive File Option

### ISSUE THREAD

**Issue by DataMedics** [neundorf/CuteCom#48]
The program has a send file button, but not a receive file button.  Often in data recovery, we need to transfer files both ways.  We command the drive to send a firmware file, but need an option in the software to receive it.  Hyperterminal could do this, but it seems to be a lacking feature in most other serial programs I've looked at.

**Comment by cyc1ingsir** [comment]
How would the start and end of the file send from the device being recognized? Using the logfile is no workaround, I assume?

**Comment by DataMedics** [comment]
It uses ymodem as the protocol to send/receive files.  I'm not exactly sure, but I believe the first block of data sent using ymodem contains the files size / name / timestamp.

**Comment by cyc1ingsir** [comment]
CuteCom relies on rzsz (X-, Y-, and Z-Modem Data Transfer Protocols) being installed to send files using these protocols (https://github.com/neundorf/CuteCom/blob/master/mainwindow.cpp#L803).
The ymodem protocol isn't implemented within CuteCom's sources. At the first glance rzsz may not be used to actually receive a file.

**Comment by cyc1ingsir** [comment]
Issue moved to https://gitlab.com/cutecom/cutecom/issues/48
