### ISSUE TITLE
To add support for Baud Rate 3 Mbps or higher

### ISSUE THREAD

**Issue by survinderpal** [neundorf/CuteCom#50]
I need to add support for 3 Mbps or higher support in CuteCom. I tried it by modifying m_combo_Baud in control.cpp. During make process, it flashed an error regarding "not supported by QSerialPort". It was found that QSerialPort does not include 921600 baud rate which is supported by CuteCom. Is there any way to add support for 3 Mbps? Please enlighten me with your thoughts.

**Comment by slapab** [comment]
Cutecom has the ability to set custom baudrate (the last option in the baudrate combobox), but currently there is a validator that prevents to enter value greater than 999000 ([code: constructor of validator](https://github.com/neundorf/CuteCom/blob/890ebb8c3a111f5e18f2fe0ea116e89d08f7e905/controlpanel.cpp#L40)). You can try to change the maximum value of that validator and recompile.

I have tried this locally and setting value greater than 1000000 worked, but my usb-uart converters could not  propery send data with that speed - probably this is just hardware limitation.
