### ISSUE TITLE
[Feature request] Monospace font

### ISSUE THREAD

**Issue by diggit** [neundorf/CuteCom#52]
Hi,
using monospace font in sent and received data view would be sometimes useful. Could you please implement font configuration or add some tick box to switch to monospace font there?

**Comment by cyc1ingsir** [comment]
Would be nice indeed.
One of the things listed in the  https://github.com/neundorf/CuteCom/blob/master/TODO

**Comment by CieNTi** [comment]
Please check PR:#62

**Comment by cyc1ingsir** [comment]
Issue moved to https://gitlab.com/cutecom/cutecom/issues/52
