### ISSUE TITLE
Add instructions on how to build project in Ubuntu to encourage development

### ISSUE THREAD

**Issue by vlouvet** [neundorf/CuteCom#53]
Step 1:  If you don't already have the code, get the latest copy using Git
`git clone https://github.com/neundorf/CuteCom.git`

Step 2: Enter CuteCom directory
`cd Cutecom`

Step 3: obtain libraries required to build executable
`sudo apt install -y qtbase5-dev cmake libqt5serialport5-dev`

Step 4: configure the build environment in preparation for compiling
`cmake .`

Step 5: compile the code into an executable file
`make `
Tip: add -j(number_of_cpu_cores) to speed up compile time. example: `make -j8 `

Step 6: (Optional) install executable into system bin directory for system-wide use.
`sudo make install`

I tested these steps and can confirm they work 100% on a clean install of Ubuntu 17.04

Perhaps someone could add some steps for enabling debug flags and other such compile options.

**Comment by johndoe71rus** [comment]
please add script to build *.deb package too

**Comment by cyc1ingsir** [comment]
Issue moved to https://gitlab.com/cutecom/cutecom/issues/53
