### ISSUE TITLE
[Feature request] Ability to preset RTS and DTR signals prior opening port

### ISSUE THREAD

**Issue by diggit** [neundorf/CuteCom#55]
As title says. Mentioned in #54.

**Comment by diggit** [comment]
How to indicate that change will not affect port until opening?

**Comment by cyc1ingsir** [comment]
Shouldn't that be part of the (session-) settings anyway. That means two more options needed to be added to the settings drawer. RTS on open [ ] , DTR on open [ ]
This needs to be stored to the settings and applied when the session is been chosen (e.g. on starting the program).
Changes to the above suggested settings options needed to be applied to the RTS, DTR switches sitting with the "device row" always too.

**Comment by cyc1ingsir** [comment]
Issue moved to https://gitlab.com/cutecom/cutecom/issues/55
