### ISSUE TITLE
Transfer to organisation account - CuteCom/CuteCom

### ISSUE THREAD

**Issue by cyc1ingsir** [neundorf/CuteCom#58]
I just noticed, that continuous integration on travis has been broken.
Setting up travis on the upstream/main repository would be helpful evaluating pull request. Being a collaborator 'only', I have not access to the settings of this repo. Hence I cannot setup a travis instance for it.

Transferring the CuteCom project to it's own organisations might make it more attractive for new developers if they could apply for being a collaborator themself more easily. Maybe that's wishful thinking, but I've seen this on other open source projects.

Anyway. The other benefit would be, that the chances the project will not being the abandoned in the future increase, if more developers are part of that organisation.

Who knows. Someone might just being inclined to create a github page for this very fine piece of software ;-)

@neundorf what do you think?

https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization
after a organization was created:
https://help.github.com/articles/collaborating-with-groups-in-organizations/

**Comment by cyc1ingsir** [comment]
In the lights of recent events, I'd like to transfer further development over to GitLab to a sort of organisational account.
I'm very happy to notice some momentum at the development within the last couple of weeks which I do not want to throttle at any case.
I would be happy to invite contributors to collaborators within this account.
However, the transfer could only be complete with the help of @neundorf . 
He would need to create an API access token, without no issues and pr history could be moved.
The main benefit would be the possibility to setup some proper CI.
I opened an initial repository at https://gitlab.com/cutecom/cutecom which can bee seen when logged in at GitLab only at the moment. This is done on purpose to prevent confusion of people looking for the original source.
This repository would remain with a notice linking to the new main one.
Any thoughts on this are welcome.

**Comment by dimtass** [comment]
Hi Meinhard,

I'm fine with the moving. I've also moved my personal repos to
bitbucket for other personal reasons.

Regarding the contribution, I would definitely add new features
that I would like to have or need in cutecom.

I'll create an account during this week.
Tschüs.

**Comment by cyc1ingsir** [comment]
Moved: https://gitlab.com/cutecom/cutecom/

**Comment by dimtass** [comment]
Very nice Meinhard.
I've also seen you use a builder in gitlab, really interesting feature.
