### ISSUE TITLE
Sending control characters

### ISSUE THREAD

**Issue by drjasonharrison-vp-eio** [neundorf/CuteCom#78]
Using CuteCom 0.45.0 on macOS 10.13.6 I cannot send control characters nor see the control character popup.

The Readme.md says: 
"Pressing Ctrl will open a widget allowing you to add control characters into the input field."

So I put my cursor focus in the Input field, press the Ctrl key, no popup. Type Control-C, press enter. No evidence from the  device or CuteCom that the Control-C character was sent.

**Comment by cyc1ingsir** [comment]
Hi,
first of all, I'm happy to hear that CuteCom in it's current version is working on macOS too.
About the Ctrl modifier, my past experience with macOS was, that quite a few of the shortcuts known from the PC world in combination with the Ctrl key would work using the Command-Key in macOS.
This fits with statement I found at: https://doc.qt.io/archives/qq/qq18-macfeatures.html

> The Command modifier is represented by the generic Qt::ControlModifier flag: 

So could you please try if the Command key is working?

This is the relevant section within the code:
https://github.com/neundorf/CuteCom/blob/01d5c57f775f1cb8c7ea7a19e16801c2e468a204/mainwindow.cpp#L281

**Comment by drjasonharrison-vp-eio** [comment]
Yes, thanks! That works well, the command key opens up the palette of characters, clicking on Ctrl-C and pressing enter sends the Ctrl-C character!
The Ctrl-C character is also added to the recent inputs so I can send it easily. Sadly the character looks like a little squiggle:
![screenshot](https://user-images.githubusercontent.com/40045831/43409312-69f7714a-93d8-11e8-8bd4-8af22edfb10e.png)
